fix seekLeaderStore NPE
tikv/client-java pull request #366
Opened 2021-12-07 08:23 UTC by iosmanthus

### What problem does this PR solve? 

This pull request fixes the NPE triggered by the double retry of `seekLeaderStore`. These buggy lines would also introduce another issue like `peer id not match` because the meta of the region is not updated.

### What is changed and how it works?

Once we change detected a reachable store we need to update the peer information of the region and retry in the most outside code.

### Check List 

Tests 

 - Integration test
 - Manual test (add detailed scripts or steps below)

Code changes

 - Has exported function/method change
 - Has exported variable/fields change
 - Has interface methods change
 - Has persistent data change

Side effects

 - Possible performance regression
 - Increased code complexity
 - Breaking backward compatibility

Related changes

 - Need to cherry-pick to the release branch
 - Need to update the documentation
 - Need to be included in the release note

2021-12-07 08:38 UTC, marsishandsome approved these changes
LGTM

2021-12-07 08:38 UTC, marsishandsome commented
/run-all-tests

2021-12-07 14:21 UTC, zz-jason commented
@iosmanthus please remove the necessary checks in PR description

2021-12-07 14:23 UTC, zz-jason requested changes
could you add some tests?

2021-12-08 03:18 UTC, iosmanthus commented
> could you add some tests?

It is really hard to inject the error to trigger a double retry of seekLeaderStore. We can only use integration to cover this case.

2021-12-09 08:27 UTC, zz-jason approved these changes
LGTM

2021-12-09 08:29 UTC, merged