Make check health timeout and period Configurable to be AP friendly
tikv/client-java pull request #369
Opened 2021-12-08 10:59 UTC by humengyu2012

Fix warning in OLAP engine:
```
2021-12-08 05:18:47,334 WARN  org.tikv.common.region.StoreHealthyChecker                   [] - store [tikv_host:tikv_port] is not reachable
2021-12-08 05:19:01,130 WARN  org.tikv.common.region.AbstractRegionStoreClient             [] - forward request to store [tikv_host:tikv_port] for region[174126738]
2021-12-08 05:19:01,894 WARN  org.tikv.common.region.StoreHealthyChecker                   [] - store [tikv_host:tikv_port] is not reachable
2021-12-08 05:19:01,933 WARN  org.tikv.common.region.StoreHealthyChecker                   [] - store [tikv_host:tikv_port] recovers to be reachable and canforward
2021-12-08 05:19:05,490 WARN  org.tikv.common.region.StoreHealthyChecker                   [] - store [tikv_host:tikv_port] is not reachable
2021-12-08 05:19:05,604 WARN  org.tikv.common.region.StoreHealthyChecker                   [] - store [tikv_host:tikv_port] recovers to be reachable and canforward
```

2021-12-08 11:29 UTC, zz-jason requested changes
could you add some tests?

2021-12-08 13:52 UTC, sunxiaoguang commented
You can have a test to verify default config. In addition, there should be an issue for this PR.

2021-12-09 11:44 UTC, zz-jason approved these changes
LGTM

2021-12-09 12:00 UTC, sunxiaoguang commented
/run-all-tests

2021-12-09 12:21 UTC, sunxiaoguang approved these changes

2021-12-09 12:21 UTC, sunxiaoguang commented
/merge

2021-12-10 08:16 UTC, sunxiaoguang commented
There is a conflicting to be resolved @humengyu2012

2021-12-10 08:24 UTC, sunxiaoguang commented
/run-all-tests

2021-12-10 13:56 UTC, sunxiaoguang commented
/run-all-tests

2021-12-10 14:07 UTC, sunxiaoguang commented
/merge

2021-12-10 15:55 UTC, merged