[WIP] reduce granularity 嗯
tikv/client-java pull request #638
Opened 2022-07-28 11:21 UTC by iosmanthus

Signed-off-by: iosmanthus <myosmanthustree@gmail.com>

### What problem does this PR solve?

Issue Number: close #issue_number

Problem Description: **TBD**

### What is changed and how does it work?

### Code changes

- Has exported function/method change
- Has exported variable/fields change
- Has methods of interface change
- Has persistent data change
- No code

### Check List for Tests

This PR has been tested by at least one of the following methods:
- Unit test
- Integration test
- Manual test (add detailed scripts or steps below)
- No code

### Side effects

- Possible performance regression, WHY: **TBD**
- Increased code complexity, WHY: **TBD**
- Breaking backward compatibility, WHY: **TBD**
- NO side effects

### Related changes

- Need to cherry-pick to the release branch
- Need to update the documentation
- Need to be included in the release note
- NO related changes

2022-07-29 10:30 UTC, xuanyu66 commented on src/main/java/org/tikv/common/PDClient.java
> +  public boolean trySwitchLeader(String leaderUrlStr) {
This method is not Thread-safe, since the value of pdClientWrapper can be changed during statements

2022-07-29 10:33 UTC, xuanyu66 requested changes

2022-07-29 10:33 UTC, xuanyu66 commented on src/main/java/org/tikv/common/PDClient.java
> +          pdClientWrapper.get() != null
The same as above, loss of atomicity

2022-07-29 10:33 UTC, xuanyu66 commented on src/main/java/org/tikv/common/PDClient.java
> +        if (pdClientWrapper.get() != null
The same as above, loss of atomicity

2022-07-31 12:37 UTC, sunxiaoguang approved these changes

2022-07-31 12:43 UTC, merged